# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'MusicDoge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicDoge
  pod 'Alamofire', '~> 5.4'

  target 'MusicDogeTests' do
    # Pods for testing
  end

end

target 'MusicDogeApps' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicDogeApps

end
